### PR TITLE
Bug 1288140: Update plugin for presto-0.150 release

### PR DESCRIPTION
**Pull request by fbertsch**
Ready for review.

---

This change is [Reviewable](https://reviewable.io/reviews/vitillo/presto-hyperloglog/1)

### CODE REVIEW

**Comment by vitillo** [comment]
Please update `classes/artifacts/presto_hyperloglog_jar/presto-hyperlolog.jar`. 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/test/java/com/mozilla/presto/hyperloglog/TestHyperLogLogQueries.java, line 84 [r1]](https://reviewable.io:443/reviews/vitillo/presto-hyperloglog/1#-KPIgiRQ5F8DDTXLyVY4:-KPIgiRQ5F8DDTXLyVY5:ba86qz) ([raw file](https://github.com/vitillo/presto-hyperloglog/blob/82e77e6eeda6ba9c1671f3593c79d088083dfc34/src/test/java/com/mozilla/presto/hyperloglog/TestHyperLogLogQueries.java#L84)):_

> ``` Java
>         }
> 
>         List<SqlFunction> hllFuns = Iterables.getOnlyElement(
> ```

Please rename the variable to `hllFunctions` and remove the line break.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/presto-hyperloglog/1#-:-KPIgtii2kxv22_xnT4A:b-32cm14)_

**Comment by vitillo** [comment]
Please verify that the plugin works as expected in a local deployment.  

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/presto-hyperloglog/1#-:-KPIinIeRArDtCUlS4zg:b-bj714j)_

**Comment by fbertsch** [comment]
I have verified that the functions work locally. Next we need to test on the cluster.

**Comment by vitillo** [comment]
We are good to go once you update the `jar` file.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/presto-hyperloglog/1#-:-KPNbktKgkuEH-U5287z:b5t2m5w)_

**Comment by fbertsch** [comment]
The previous artifact wouldn't build for me. I put in maven specifications so that we can continue to build a jar that contains all dependencies in the pom.

@vitillo r?

**Comment by vitillo** [comment]
@fbertsch could you please update the documentation with the steps necessary to generate the jar file?

---

Reviewed 1 of 1 files at r4.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/presto-hyperloglog/1#-:-KQuPfXO6Xb8lYCB7WJF:b66mns4)_

**Comment by fbertsch** [comment]
Added documentation for ensuring the plugin works as intended when building the uber jar with maven. @vitillo, ready for merge?

**Comment by fbertsch** [comment]
Updated the documentation, and uber jar now resides in target, with the version appended. Ping @vitillo

**Comment by vitillo** [comment]
@fbertsch can you please rename the current jar as well to adhere to the new naming convention?

**Comment by vitillo** [comment]
Looks good, thanks!

**Pull request merged**
