### PR TITLE
Update plugin for presto-0.152.3 release

### PR DESCRIPTION
**Pull request by robotblake**
EMR just release 5.0.3 which includes Presto 0.152.3.

---

This change is [Reviewable](https://reviewable.io/reviews/vitillo/presto-hyperloglog/3)

### CODE REVIEW

**Comment by vitillo** [comment]
@fbertsch r?

**Comment by fbertsch** [comment]
Has this been tested on a presto machine?

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/presto-hyperloglog/3#-:-KUx81GFycZWt5ihcn9W:b-rvqywx)_

**Comment by robotblake** [comment]
Yes this has.

**Comment by fbertsch** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/presto-hyperloglog/3#-:-KVXU59m5f9AKNc8ernO:bnfp4nl)_

**Comment by fbertsch** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/presto-hyperloglog/3)_

**Pull request merged**
